### PR TITLE
fix: updated breadcrumb casing in Modify API response rule editor

### PR DESCRIPTION
**Pull request by ncharanaraj**
Closes issue: #708 

## 📜 Summary of changes:

In Lodash the "capitalize" - Converts the first character of the string to upper case and the remaining to lower case. So, I removed the capitalize function.

## ✅ Checklist:

- [ ] Make sure linting and unit tests pass.
- [ ] No install/build warnings introduced.
- [x] Verified UI in browser.
- [ ] For UI changes, added/updated analytics events (if applicable).
- [ ] For changes in extension's code, manually tested in Chrome and Firefox.
- [ ] For changes in extension's code, both MV2 and MV3 are covered.
- [ ] Added/updated unit tests for this change.
- [ ] Raised pull request to update corresponding documentation (if already exists).

### CODE REVIEW

**Comment by rohanmathur91** [comment]
@ncharanaraj Can you please add before and after change screenshots?

**Review by rohanmathur91 — CHANGES_REQUESTED** [review]
It's the rule title that is causing the issue not breadcrumb.

**Comment by ncharanaraj** [comment]
@rohanmathur91 You are right that the issue is not from the breadcrumb. However, I saw that the rule titles constants are written perfectly cased. I finally figured out the casing in which where the capitalized function is invoked and passed the rule titles as a parameter. That's why it's outputting in lowercase. So, now I have removed the function, Look at the below output and let me know if there are any changes needed otherwise, I will create a pull request for this.
Screenshot (67)

**Comment by ncharanaraj** [comment]
@rohanmathur91 Any updates on this issue I have made the changes and re-requested for review but no action has been taken on this issue so, please check and let me know.

**Comment by rohanmathur91** [comment]
The provided fix breaks the other rule titles
Screenshot 2023-06-22 at 5 00 04 PM

**Comment by ncharanaraj** [comment]
Hello, @rohanmathur91 API casing is fixed. Requesting for review.

**Review by rohanmathur91 — APPROVED** [review]

**Comment by rohanmathur91** [comment]
Thanks for contributing @ncharanaraj.

**Pull request merged**
