### PR TITLE
ENGG-2341: New environment creation flow

### PR DESCRIPTION
**Pull request by RuntimeTerror10**
Screenshot 2024-10-18 at 2 31 25 AM

### CODE REVIEW

**Comment by rohanmathur91** [comment]
When new row is added, input should be auto focus
https://github.com/user-attachments/assets/f3d9adb3-13e0-44c2-8a03-5df9818f9721

**Comment by rohanmathur91** [comment]
Why duplicate `default`?
Screenshot 2024-10-21 at 7 14 23 PM

**Comment by rohanmathur91** [comment]
Overflow issues

https://github.com/user-attachments/assets/a629410a-5dfb-46c8-9bae-91ad9d30f3e7

**Comment by rohanmathur91** [comment]
Are we not giving rename and delete environment option?

**Comment by RuntimeTerror10** [comment]
> Are we not giving rename and delete environment option?

No

**Review by rohanmathur91 — CHANGES_REQUESTED** [review]

**Comment by RuntimeTerror10** [comment]
> Why duplicate `default`? Screenshot 2024-10-21 at 7 14 23 PM

Default env are created automatically, but ignore this as we are no longer going with this flow

**Review by rohanmathur91 — APPROVED** [review]

**Pull request merged**
