### PR TITLE
fix: sendMessage return nothing in firefox

### PR DESCRIPTION
**Pull request by Lyrillind**
Problem:
After install in firefox, click the icon in toolbar, no popup window shows up.

Fix:
Somehow, chrome.runtime.sendMessage returns nothing, so sendMessage().then will not work and throws an error.

### CODE REVIEW

**Comment by nafees87n** [comment]
@Lyrillind Which extension version are you using in firefox? The latest version we have on firefox is `24.5.8` as MV3 APIs were not supported in firefox.

As starting Firefox 128, MV3 is fully supported. We are in the process of releasing the latest version in Firefox.

**Comment by Lyrillind** [comment]
> @Lyrillind Which extension version are you using in firefox? The latest version we have on firefox is `24.5.8` as MV3 APIs were not supported in firefox.
> 
> As starting Firefox 128, MV3 is fully supported. We are in the process of releasing the latest version in Firefox.

I built from master branch, and load MV2 in firefox 129.
When try to load MV3, firefox tells not supported.

**Comment by nafees87n** [comment]
> I built from master branch, and load MV2 in firefox 129.
 When try to load MV3, firefox tells not supported.

Yes because we do not support MV3 in firefox yet.
May I know why do you want to build and not use the production extension on firefox?

**Comment by Lyrillind** [comment]
> > I built from master branch, and load MV2 in firefox 129.
> > When try to load MV3, firefox tells not supported.
> 
> Yes because we do not support MV3 in firefox yet. May I know why do you want to build and not use the production extension on firefox?

Because I want to deploy on my persernal computer.

**Comment by nafees87n** [comment]
Thanks @Lyrillind This PR looks good. Merging...
MV3 migration in firefox will take some time. As Firefox continues to support MV2, our extension is already stable in Firefox.

**Review by nafees87n — APPROVED** [review]

**Pull request merged**
